In [6]:
import numpy as np
import matplotlib.plyplot as plt 

ModuleNotFoundError: No module named 'matplotlib.plyplot'

In [8]:
x = [10,21,3,14,15,16]
x 
type(x)   

list

In [10]:
y = np.array(x) 

In [12]:
type(y) 

numpy.ndarray

In [16]:
y[0:4]   

array([10, 21,  3, 14])

In [18]:
y.shape 

(6,)

In [20]:
y>10

array([False,  True, False,  True,  True,  True])

In [22]:
y[y>10]

array([21, 14, 15, 16])

In [24]:
y**2

array([100, 441,   9, 196, 225, 256], dtype=int32)

In [26]:
y+1

array([11, 22,  4, 15, 16, 17])

In [29]:
y[y%2!=0]

array([21,  3, 15])

In [32]:
y[y%2==0]

array([10, 14, 16])

In [49]:
x = [1,2,2,2,5,6]
y = [7,8,9,10,11,12]   

In [50]:
z = np.array([x,y])
z

array([[ 1,  2,  2,  2,  5,  6],
       [ 7,  8,  9, 10, 11, 12]])

In [51]:
z.shape

(2, 6)

In [54]:
z = z.reshape(4,3) 
z

array([[ 1,  2,  2],
       [ 2,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [55]:
z.shape

(4, 3)

In [58]:
z[0,0]

1

In [60]:
z[:,:]

array([[ 1,  2,  2],
       [ 2,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [62]:
np.mean(z)

6.25

In [64]:
np.median(z)

6.5

In [69]:
from scipy import stats
stats.mode(z,axis = None)

ModeResult(mode=array([2]), count=array([3]))

In [71]:
np.mean(z[1,:])

4.333333333333333

In [73]:
np.std(z) 

3.6996621467371855

In [75]:
np.var(z)

13.6875

In [78]:
np.round(1.21212,3)

1.212

In [80]:
np.round(2.5556565,2)

2.56

In [82]:
temp1 = np.random.normal(10,2,5)
temp1
help(np.random.normal)
temp1

Help on built-in function normal:

normal(...) method of numpy.random.mtrand.RandomState instance
    normal(loc=0.0, scale=1.0, size=None)
    
    Draw random samples from a normal (Gaussian) distribution.
    
    The probability density function of the normal distribution, first
    derived by De Moivre and 200 years later by both Gauss and Laplace
    independently [2]_, is often called the bell curve because of
    its characteristic shape (see the example below).
    
    The normal distributions occurs often in nature.  For example, it
    describes the commonly occurring distribution of samples influenced
    by a large number of tiny, random disturbances, each with its own
    unique distribution [2]_.
    
    .. note::
        New code should use the ``normal`` method of a ``default_rng()``
        instance instead; please see the :ref:`random-quick-start`.
    
    Parameters
    ----------
    loc : float or array_like of floats
        Mean ("centre") of the distribution

array([ 8.40655993, 10.05963182,  8.69653761,  9.0790872 , 11.71068121])

In [88]:
temp2 = np.random.normal(-10,2,5)
temp2

array([-12.02398985, -12.68850163, -12.96184497,  -8.68745816,
        -8.87095439])

In [91]:
temp3 = np.column_stack((temp1,temp2))
temp3

array([[  8.40655993, -12.02398985],
       [ 10.05963182, -12.68850163],
       [  8.69653761, -12.96184497],
       [  9.0790872 ,  -8.68745816],
       [ 11.71068121,  -8.87095439]])

In [93]:
a = 10
b = 20

In [95]:
a+b

30

In [96]:
a-b

-10

In [98]:
a*b

200

In [100]:
a/b

0.5

In [102]:
a//b

0

In [104]:
b%a

0

In [106]:
a%b

10

In [108]:
a**b

100000000000000000000

In [110]:
a = 15 
a == b 

False

In [112]:
a != b

True

In [114]:
a>b

False

In [116]:
a<b

True

In [128]:
c = a+b
c

35

In [137]:
c += b
c

55

In [138]:
c -= b
c

35

In [140]:
a = 60
b = 13

format(60,"b")



'111100'

In [142]:
format(13,"b") 

'1101'

In [144]:
help('FORMATTING')

Format String Syntax
********************

The "str.format()" method and the "Formatter" class share the same
syntax for format strings (although in the case of "Formatter",
subclasses can define their own format string syntax).  The syntax is
related to that of formatted string literals, but there are
differences.

Format strings contain “replacement fields” surrounded by curly braces
"{}". Anything that is not contained in braces is considered literal
text, which is copied unchanged to the output.  If you need to include
a brace character in the literal text, it can be escaped by doubling:
"{{" and "}}".

The grammar for a replacement field is as follows:

      replacement_field ::= "{" [field_name] ["!" conversion] [":" format_spec] "}"
      field_name        ::= arg_name ("." attribute_name | "[" element_index "]")*
      arg_name          ::= [identifier | digit+]
      attribute_name    ::= identifier
      element_index     ::= digit+ | index_string
      index_string      ::=

In [146]:
"i" in "nikhil" 

True

In [148]:
"p" in "nikhil"  

False

In [150]:
"p" not in "nikhil" 

True

In [154]:
"nikhil" is "Nikhil"

<>:1: SyntaxWarning: "is" with a literal. Did you mean "=="?
<>:1: SyntaxWarning: "is" with a literal. Did you mean "=="?
<ipython-input-154-2429091bc8f8>:1: SyntaxWarning: "is" with a literal. Did you mean "=="?
  "nikhil" is "Nikhil"


False

In [156]:
1 is 1 

<>:1: SyntaxWarning: "is" with a literal. Did you mean "=="?
<>:1: SyntaxWarning: "is" with a literal. Did you mean "=="?
<ipython-input-156-9f107a2fc996>:1: SyntaxWarning: "is" with a literal. Did you mean "=="?
  1 is 1


True

In [158]:
2 is not 1 

<>:1: SyntaxWarning: "is not" with a literal. Did you mean "!="?
<>:1: SyntaxWarning: "is not" with a literal. Did you mean "!="?
<ipython-input-158-f179e642ec83>:1: SyntaxWarning: "is not" with a literal. Did you mean "!="?
  2 is not 1


True

In [160]:
"Nikhil" is "Nikhil" 

<>:1: SyntaxWarning: "is" with a literal. Did you mean "=="?
<>:1: SyntaxWarning: "is" with a literal. Did you mean "=="?
<ipython-input-160-67f3bc22aa83>:1: SyntaxWarning: "is" with a literal. Did you mean "=="?
  "Nikhil" is "Nikhil"


True

In [162]:
"hi hello"  is   "hello hi" 

<>:1: SyntaxWarning: "is" with a literal. Did you mean "=="?
<>:1: SyntaxWarning: "is" with a literal. Did you mean "=="?
<ipython-input-162-b357f21c4b1e>:1: SyntaxWarning: "is" with a literal. Did you mean "=="?
  "hi hello"  is   "hello hi"


False

In [164]:
Name = "excelr"   

In [166]:
print(Name)
Name 

excelr


'excelr'

In [168]:
print(Name[-1]) 

r


In [170]:
Name[3] 

'e'

In [172]:
print(Name[1:4]) 

xce


In [174]:
print(Name[-4:-1])    

cel


In [176]:
var1 = "Hello World!"
var1 

'Hello World!'

In [178]:
out =  var1 +'Python'  

In [180]:
out 

'Hello World!Python'

In [182]:
print ("Updated  ", var1 + ' Python') 

Updated   Hello World! Python


In [184]:
print("My name is %s and weight is %.3f kgs! my  father name is %s " % ('Anil', 70,'Ramu'))  

My name is Anil and weight is 70.000 kgs! my  father name is Ramu 


In [187]:
number  = 10  #hardcoding
number   

10

In [189]:
number = input("enter num:  ")     
number  

enter num:  25


'25'

In [191]:
number = input("enter num:  ")  

enter num:  75


In [194]:
number_1 = eval(input("enter number: "))   

enter number: 72


In [196]:
Name = input("Enter your name: ")    


Enter your name: francis


In [198]:
Weight = eval(input("Enter your Weight: "))    

Enter your Weight: 72


In [200]:
(Name,Weight)   

('francis', 72)

In [203]:
Name = "ExcelR excelr"  

In [228]:
Name.lower() #lower case   

'excelr excelr'

In [207]:
Name.center(100)  

'                                           ExcelR excelr                                            '

In [209]:
Name.center(150)   

'                                                                    ExcelR excelr                                                                     '

In [211]:
Name.count("excelr")  

1

In [215]:
string = "excelr is an training institute"
substring = "e"  

In [218]:
string.count(substring)    

3

In [220]:
count = string.count(substring)
count 

3

In [222]:
("The count is:", count) 

('The count is:', 3)

In [224]:
Num = "f1234" 

In [226]:
print(Num.isalnum())   

True


In [229]:
Num = "this is string example"
Num.isalnum()  

False

In [231]:
Num = "this";  # No space & digit in this string
Num.isalpha()  

True

In [233]:
Num = "this is string example0909090!!!";
Num.isalpha() 

False

In [235]:
Num = "123456";  # Only digit in this string
Num.isdigit()  

True

In [236]:
Num = "this is string example!!!";

alpha = Num.upper()
alpha 

'THIS IS STRING EXAMPLE!!!'

In [238]:
reply = "it is string example!!! is really a string"
print(reply.replace("is", "was")) 

it was string example!!! was really a string


In [240]:
reply.replace("is", "was", 1)   
#print('was'.join(reply.rsplit('is',1))) 

'it was string example!!! is really a string'

In [242]:
#The following example shows the usage of split() method.
split1 = "Line1-abcdef,nLine2-abc,nLine4-abcd"
split1.split(",")  

['Line1-abcdef', 'nLine2-abc', 'nLine4-abcd']

In [244]:
list1 = ['Nikhil', 'Excelr', 2013, 2018];
list1 

['Nikhil', 'Excelr', 2013, 2018]

In [246]:
del(list1[2]) 
list1 

['Nikhil', 'Excelr']

In [248]:
aList = [123, 'xyz', 'zara', 'abc'] 
aList.append( 2009 )
aList 

[123, 'xyz', 'zara', 'abc', 2009]

In [250]:
print (aList.pop(1))

zara


In [252]:
aList = [123, 'xyz', 'tommy', 'abc', 123];
bList = [2009, 'beneli']; 

In [254]:
aList.extend(bList)
aList 

[123, 'xyz', 'tommy', 'abc', 123, 2009, 'beneli', 2009, 'beneli']

In [258]:
aList.reverse(); 
aList

[123, 'xyz', 'tommy', 'abc', 123, 2009, 'beneli', 2009, 'beneli']

In [260]:
blist = [8,99,45,33]
blist.sort();
blist 

[8, 33, 45, 99]

In [262]:
tup1 = ('Street triple','Detona','Beneli', 8055);
print(tup1[0]); 

Street triple


In [264]:
tup2 = (1, 2, 3, 4, 5, 6, 7 );
print(tup2[1:5]); 

(2, 3, 4, 5)


In [266]:
dict1 = {'Name': 'Nikhil', 'Age': 25, 'bike': 'Beneli'}
print(dict1) 

{'Name': 'Nikhil', 'Age': 25, 'bike': 'Beneli'}


In [268]:
dict1['Name'] 

'Nikhil'

In [270]:
print(dict1['Age'])   
print(dict1['bike'])

25
Beneli


In [272]:
dict1 = {'Name': 'Nikhil', 'Age': 25, 'bike': 'Beneli'}
dict1['Age'] = 8; # update existing entry
dict1['School'] = "DPS School"; # Add new entry
dict1['Sal'] = 50000;

print(dict1['Age'])
print(dict1['Sal'])  

8
50000


In [274]:
# Creating a data frame manually from lists 
new_df = pd.DataFrame(columns=["A","B","C"])
new_df["A"] = pd.Series([1,2,3,4,5,6])    
new_df["B"] = pd.Series(["A","B","C","D"])   
new_df["C"] = pd.Series([True,False,True,False])  

In [276]:
new_df 

A    B      C
0  1    A   True
1  2    B  False
2  3    C   True
3  4    D  False
4  5  NaN    NaN
5  6  NaN    NaN

In [278]:
new_df.drop(["A"],axis=1)  

B      C
0    A   True
1    B  False
2    C   True
3    D  False
4  NaN    NaN
5  NaN    NaN

In [283]:
mba = pd.read_csv("mba.csv")

In [284]:
pd.set_option("display.max_rows", None) 
mba

datasrno  workex  gmat
0           1      21   720
1           2     107   640
2           3      57   740
3           4      99   690
4           5     208   710
5           6     136   660
6           7      70   660
7           8     103   710
8           9      79   700
9          10      22   730
10         11      69   700
11         12      41   740
12         13      72   650
13         14      69   720
14         15      20   700
15         16      21   760
16         17      19   710
17         18      86   720
18         19     231   690
19         20      20   770
20         21     175   660
21         22      21   710
22         23      44   720
23         24      23   650
24         25      20   710
25         26      70   720
26         27      46   710
27         28      33   650
28         29     130   690
29         30      57   690
30         31      57   750
31         32      45   710
32         33      55   730
33         34      42   770
34         35      34   690
35         36      55   710
36         37      44   710
37         38      79   710
38         39      45   740
39         40      38   720
40         41      44   710
41         42      83   720
42         43     118   650
43         44      45   710
44         45      89   690
45         46      77   700
46         47      91   730
47         48      61   690
48         49      47   670
49         50      69   710
50         51      59   720
51         52      32   710
52         53      74   740
53         54     279   750
54         55      33   710
55         56      33   730
56         57      34   730
57         58     110   710
58         59      44   710
59         60      44   690
60         61      46   720
61         62      58   690
62         63      45   710
63         64      34   720
64         65      54   770
65         66      45   720
66         67      33   740
67         68      82   710
68         69      72   740
69         70      77   710
70         71      43   740
71         72      54   740
72         73      92   730
73         74      90   720
74         75      66   760
75         76      38   720
76         77      25   740
77         78      57   740
78         79      31   710
79         80      58   690
80         81      55   710
81         82      68   710
82         83      79   730
83         84      71   700
84         85      68   710
85         86      32   750
86         87      32   710
87         88      45   710
88         89      69   720
89         90      65   680
90         91      57   710
91         92      45   710
92         93      92   710
93         94      57   740
94         95      69   710
95         96      32   710
96         97      70   700
97         98      59   690
98         99      44   770
99        100      44   770
100       101      46   720
101       102      33   730
102       103      46   710
103       104      82   720
104       105      53   690
105       106      33   740
106       107      34   690
107       108      37   690
108       109      55   750
109       110      52   720
110       111      68   670
111       112      51   690
112       113      69   710
113       114      47   690
114       115      56   750
115       116      45   710
116       117      56   680
117       118      48   690
118       119      34   730
119       120      55   750
120       121      43   700
121       122      69   720
122       123      31   680
123       124      46   690
124       125      58   700
125       126      47   740
126       127      56   710
127       128      43   730
128       129      58   720
129       130      27   720
130       131      46   740
131       132      58   680
132       133      34   670
133       134      34   730
134       135      45   680
135       136      68   710
136       137      34   740
137       138      46   760
138       139      45   710
139       140      56   710
140       141      33   710
141       142      33   730
1

In [286]:
pd.set_option("display.max_rows", None) 
data = mba.drop(mba.index[[5,9,19]],axis=0)
data

datasrno  workex  gmat
0           1      21   720
1           2     107   640
2           3      57   740
3           4      99   690
4           5     208   710
6           7      70   660
7           8     103   710
8           9      79   700
10         11      69   700
11         12      41   740
12         13      72   650
13         14      69   720
14         15      20   700
15         16      21   760
16         17      19   710
17         18      86   720
18         19     231   690
20         21     175   660
21         22      21   710
22         23      44   720
23         24      23   650
24         25      20   710
25         26      70   720
26         27      46   710
27         28      33   650
28         29     130   690
29         30      57   690
30         31      57   750
31         32      45   710
32         33      55   730
33         34      42   770
34         35      34   690
35         36      55   710
36         37      44   710
37         38      79   710
38         39      45   740
39         40      38   720
40         41      44   710
41         42      83   720
42         43     118   650
43         44      45   710
44         45      89   690
45         46      77   700
46         47      91   730
47         48      61   690
48         49      47   670
49         50      69   710
50         51      59   720
51         52      32   710
52         53      74   740
53         54     279   750
54         55      33   710
55         56      33   730
56         57      34   730
57         58     110   710
58         59      44   710
59         60      44   690
60         61      46   720
61         62      58   690
62         63      45   710
63         64      34   720
64         65      54   770
65         66      45   720
66         67      33   740
67         68      82   710
68         69      72   740
69         70      77   710
70         71      43   740
71         72      54   740
72         73      92   730
73         74      90   720
74         75      66   760
75         76      38   720
76         77      25   740
77         78      57   740
78         79      31   710
79         80      58   690
80         81      55   710
81         82      68   710
82         83      79   730
83         84      71   700
84         85      68   710
85         86      32   750
86         87      32   710
87         88      45   710
88         89      69   720
89         90      65   680
90         91      57   710
91         92      45   710
92         93      92   710
93         94      57   740
94         95      69   710
95         96      32   710
96         97      70   700
97         98      59   690
98         99      44   770
99        100      44   770
100       101      46   720
101       102      33   730
102       103      46   710
103       104      82   720
104       105      53   690
105       106      33   740
106       107      34   690
107       108      37   690
108       109      55   750
109       110      52   720
110       111      68   670
111       112      51   690
112       113      69   710
113       114      47   690
114       115      56   750
115       116      45   710
116       117      56   680
117       118      48   690
118       119      34   730
119       120      55   750
120       121      43   700
121       122      69   720
122       123      31   680
123       124      46   690
124       125      58   700
125       126      47   740
126       127      56   710
127       128      43   730
128       129      58   720
129       130      27   720
130       131      46   740
131       132      58   680
132       133      34   670
133       134      34   730
134       135      45   680
135       136      68   710
136       137      34   740
137       138      46   760
138       139      45   710
139       140      56   710
140       141      33   710
141       142      33   730
142       143      44   680
143       144      33   690
144       145      69   720
1

In [288]:
# using if and else conditional statements 
def check_even(i):
    # function body
    if i%2==0:
        print ("even")
    else:
        print ("odd") 

In [289]:
check_even(510)   

even


In [291]:
x = [1,2,[1,2,4],43,54]  

In [293]:
# For loop syntax 
for i in x:
    print (i)   

1
2
[1, 2, 4]
43
54


In [294]:
for i in range(10):
    print (i) 

0
1
2
3
4
5
6
7
8
9


In [295]:
for i in range(1,10,2):
    print (i)  

1
3
5
7
9


In [296]:
# while loop syntax 
i = 1
while i < 10:
    print (i)
    i= i+1  

1
2
3
4
5
6
7
8
9


In [298]:
x = [[1,2],[1,2,4],[43],[54],[2,3,4]] 

In [299]:
# using break operation to terminate any for loop in middle
for i in x:
    if len(i)>2:
        break
    else:
        print (i) 

[1, 2]


In [300]:
# Creating a data frame manually from lists 
new_df = pd.DataFrame(columns=["A","B","C"])
new_df["A"] = pd.Series([1,2,3,4,5,6])    
new_df["B"] = pd.Series(["A","B","C","D"])   
new_df["C"] = pd.Series([True,False,True,False])  

In [301]:
new_df 

A    B      C
0  1    A   True
1  2    B  False
2  3    C   True
3  4    D  False
4  5  NaN    NaN
5  6  NaN    NaN